Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.provider "virtualbox" do |v|
    v.name = "vbox1"
    v.memory = 1024
    v.cpus = 2
  end
  config.vm.network "private_network", type: "dhcp"
end
