CREATE DATABASE open_fec;
USE open_fec;
 
CREATE TABLE all_candidates (
	CAND_ID	VARCHAR(9),
    CAND_NAME VARCHAR(200),
    CAND_ICI VARCHAR(10),
    PTY_CD VARCHAR(10),
    CAND_PTY_AFFILIATION VARCHAR(10),
    TTL_RECEIPTS VARCHAR(14),
    TRANS_FROM_AUTH VARCHAR(14),
    TTL_DISB VARCHAR(14),
    TRANS_TO_AUTH VARCHAR(14),
    COH_BOP VARCHAR(14),
    COH_COP VARCHAR(14),
    CAND_CONTRIB VARCHAR(14),
    CAND_LOANS  VARCHAR(14),
    OTHER_LOANS	VARCHAR(14),
    CAND_LOAN_REPAY	VARCHAR(14),
    OTHER_LOAN_REPAY VARCHAR(14),
    DEBTS_OWED_BY VARCHAR(14),
    TTL_INDIV_CONTRIB VARCHAR(14),
    CAND_OFFICE_ST VARCHAR(14),
    CAND_OFFICE_DISTRICT VARCHAR(14),
    SPEC_ELECTION VARCHAR(14),
    PRIM_ELECTION VARCHAR(14),
    RUN_ELECTION VARCHAR(14),
    GEN_ELECTION VARCHAR(14),
    GEN_ELECTION_PERCENT VARCHAR(14),
    OTHER_POL_CMTE_CONTRIB VARCHAR(14),
    POL_PTY_CONTRIB VARCHAR(14),
    CVG_END_DT VARCHAR(20),
    INDIV_REFUNDS VARCHAR(14),
    CMTE_REFUNDS VARCHAR(14)
);

SET SESSION sql_mode = '';
DROP TABLE all_candidates;
SELECT CAND_NAME FROM all_candidates
ORDER BY CAND_NAME;
