CREATE TABLE individual_contributions(
	CMTE_ID	VARCHAR(15),
    AMNDT_IND VARCHAR(4),
    RPT_TP VARCHAR(5),
    TRANSACTION_PGI	VARCHAR(7),
    IMAGE_NUM VARCHAR(20),
    TRANSACTION_TP VARCHAR(5),
    ENTITY_TP VARCHAR(5),
    NAME VARCHAR(200),
    CITY VARCHAR(30),
    STATE VARCHAR(4),
    ZIP_CODE VARCHAR(13),
    EMPLOYER VARCHAR(40),
    OCCUPATION VARCHAR(40),
    TRANSACTION_DT VARCHAR(12),
    TRANSACTION_AMT	VARCHAR(20),
    OTHER_ID VARCHAR(11),
    TRAN_ID VARCHAR(35),
    FILE_NUM VARCHAR(24),
    MEMO_CD	VARCHAR(4),
    MEMO_TEXT VARCHAR(100),
    SUB_ID VARCHAR(21)
);

SELECT COUNT(FILE_NUM) FROM individual_contributions;
DROP TABLE individual_contributions;